# Source - https://stackoverflow.com/a
# Posted by Delta George
# Retrieved 2025-12-05, License - CC BY-SA 4.0

name: Matrix workflow
on: push

jobs:
  gather-data:
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.diff-files.outputs.components }}
    steps:
      - name: git diff
        id: diff-files
        run: |
          {
            echo '{"foo": 10, "bar": 20}'
            echo '{"foo": 12, "bar": 22}'
          } > components.json
          echo components=$(jq -c --slurp '.' components.json) > $GITHUB_OUTPUT

  slack-post:
    needs: gather-data
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    strategy:
      matrix:
        include: ${{ fromJSON(needs.gather-data.outputs.values) }}
    steps:
      - run: echo ${{ matrix.foo }} ${{ matrix.bar }}
